# Generated by Django 5.0.4 on 2024-04-28 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('UNKNOWN', 'Unknown')], max_length=100)),
                ('oldRating', models.IntegerField(default=100)),
                ('currentRating', models.IntegerField(default=100)),
                ('opponentOne', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opponent_one', to='chessweb.player')),
                ('opponentThree', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opponent_three', to='chessweb.player')),
                ('opponentTwo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opponent_two', to='chessweb.player')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_letter', models.CharField(max_length=2)),
                ('board_number', models.IntegerField()),
                ('result', models.CharField(choices=[('WHITE_WIN', 'White Win'), ('BLACK_WIN', 'Black Win'), ('DRAW', 'Draw'), ('STALEMATE', 'Stalemate'), ('UNKNOWN', 'Unknown'), ('BLANK', '')], max_length=100)),
                ('black_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playerB', to='chessweb.player')),
                ('white_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playerW', to='chessweb.player')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chessweb.player')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chessweb.userclub')),
            ],
        ),
        migrations.CreateModel(
            name='UserGroupPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chessweb.userclub')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chessweb.player')),
            ],
        ),
    ]
